<?php
$collection = $block->getSliderCollection();
$slidercount = 0;
$slidercount     = $collection->count();
$mediaUrl = $block->getMediaUrl();
if ($slidercount > 0) {
    ?>
<div class="main_home_slider_section">
    <div class="main_home_slider owl-carousel owl-theme">
        <?php foreach ($collection as $slider) { ?>
        <div>
            <div class="main_home_slider-img <?= /* @noEscape */ $slider->getTextPosition();?>"
            href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->getUrlKey() :
            "javascript:void(0)" ?>" <?php if (!empty($slider->getUrlKey())) { ?> target="_blank" <?php } ?>>
                
                <picture>
                    <source media="(min-width: 750px)" srcset="<?=
                    $block->escapeHtml($mediaUrl.$slider->getImagename()) ?>">
                    <source media="(max-width: 749px)" srcset="<?php
                        $imageUrl='';
                    if (strlen($slider->getMobileimagename())==0) {
                        $imageUrl=$slider->getImagename();
                    } else {
                        $imageUrl=$slider->getMobileimagename();
                    }
                    echo $block->escapeHtml($mediaUrl.$imageUrl); ?>">
                    <img src="<?php
                            $imageUrl='';
                    if (strlen($slider->getMobileimagename())==0) {
                        $imageUrl=$slider->getImagename();
                    } else {
                        $imageUrl=$slider->getMobileimagename();
                    }
                    $block->escapeHtml($mediaUrl.$imageUrl); ?>" alt="<?= $block->
                    escapeHtml($slider->getTitle()) ?>" title="<?= $block->escapeHtml($slider->getTitle()) ?>" >
                </picture>
                <?php
                    $f=0;
                if ($slider->getSlidertitle()) {
                    $f=1;
                }
                if ($slider->getButtontitle()) {
                    $f=1;
                }
                if ($f==1) {
                    ?>
                <div class="main_home_slider-info" >
                    <div class="main_home_slider-info-inner">
                    <?php if ($slider->getSlidertitle()) { ?>
                        <h3 class="main_home_slider-info-title"><?= $block->
                        escapeHtml($slider->getSlidertitle()) ?></h3>
                    <?php } ?>
                    <?php
                    if ($slider->getButtontitle()) {
                        if ($slider->getOpenNewTab()=='1') {
                            ?>

                    <a href="<?= /* @noEscape */ ($slider->getUrlKey()) ? $slider->
                    getUrlKey() : "javascript:void(0)" ?>" <?php if (!empty($slider->getUrlKey())) {
    ?> target="_blank" <?php } ?>
                    class="main_home_slider-info-button action"><?= $block->escapeHtml($slider->getButtontitle()) ?></a>

                  <?php } else {?>
                    <a href="<?= /* @noEscape */ (
                        $slider->getUrlKey()) ? $slider->getUrlKey() : "javascript:void(0)" ?>"
                            <?php if (!empty($slider->getUrlKey())) {
                                ?>  <?php } ?> class="main_home_slider-info-button action"><?=
                            $block->escapeHtml($slider->getButtontitle()) ?></a>
              <?php }}?>
                    </div> 
                </div>
            <?php } ?>
            </div>
        </div>
        <?php } ?>
    </div>
</div>

    <?php
    $autoPlayspeed=7000;
    if (strlen($block->getSystemConfig('bannerslider/slider/autoplay_timing'))>0) {
        $autoPlayspeed=$block->getSystemConfig('bannerslider/slider/autoplay_timing');
    }

    $direction='false';
    if ($block->getSystemConfig('announcementbar/slider/text_direction')=='left-to-right') {
        $direction='true';
    }
    ?>
<script type="application/javascript">
    require(["jquery","navigate/bannerslider/owl.carousel"],function($) {
        $('.main_home_slider').css('display', "block").owlCarousel({
            loop: <?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/infinite'); ?>,
            responsiveClass:true,
            dots:<?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/show_dots'); ?>,
            autoplay: <?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/autoplay'); ?>,
            autoplayTimeout: <?= /* @noEscape */ $autoPlayspeed;?>,
            nav:<?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/show_arrow'); ?>,
            responsive : {
                0:{
                    nav:false,
                    items:<?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/item_mobile'); ?>
                },
                768:{
                    nav:<?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/show_arrow'); ?>,
                    items:<?= /* @noEscape */ $block->getSystemConfig('bannerslider/slider/item_desktop'); ?>
                }
            }
        });
         window.dispatchEvent(new Event('resize'));
    });
</script>
<?php } else { ?>
<div class="message info empty">
    <div><?= /* @escapeNotVerified */ $block->escapeHtml(__(
        'We can\'t find banner slider matching the selection.'
    )) ?></div>
</div>
<?php } ?>
